server:
  port: 8082
  session:
    cookie:
      name: UISESSION
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          custom-client:
            client-id: myclient
            client-secret: secret
            client-name: Auth Server
            scope: read
            provider: custom-provider
            redirect-uri : http://localhost:8082/redirect
            client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            token-uri: http://localhost:8081/oauth/token
            authorization-uri: http://localhost:8081/oauth/authorize
            user-info-uri: http://localhost:8081/user/me
            user-name-attribute: name